# Generated by Django 4.0.2 on 2023-11-09 06:33

from django.db import migrations, models
import django.db.models.deletion
import helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('tel', models.CharField(default='', max_length=80)),
            ],
            bases=(helpers.models.NameMixin, helpers.models.AgeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('tel', models.CharField(default='', max_length=80)),
                ('address', models.CharField(default='', max_length=80)),
                ('orientation', models.CharField(default='', max_length=80)),
                ('level', models.CharField(default='', max_length=80)),
                ('curriculum', models.CharField(default='', max_length=80)),
                ('county', models.CharField(default='', max_length=80)),
                ('sub_county', models.CharField(default='', max_length=80)),
                ('location', models.CharField(default='', max_length=80)),
                ('student_population', models.IntegerField()),
                ('teacher_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('tel', models.CharField(default='', max_length=80)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.school')),
            ],
            bases=(helpers.models.NameMixin, helpers.models.AgeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=80)),
                ('disability', models.CharField(choices=[('NONE', 'None'), ('BLIND', 'Vision Impairment'), ('DEAF', 'Hard of Hearing'), ('AUTISM', 'Autism'), ('PHYSICAL IMPAIRMENT', 'Physical Impairment'), ('COGNITIVE', 'Cognitive Impairment'), ('PSYCHOLOGICAL', 'Psychological Impairment')], default='none', max_length=20)),
                ('grade', models.IntegerField()),
                ('stream', models.CharField(default='', max_length=80)),
                ('uid', models.IntegerField()),
                ('date_joined', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.school')),
            ],
            bases=(helpers.models.NameMixin, helpers.models.AgeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('date_reported', models.DateField()),
                ('date_solved', models.DateField()),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.student')),
            ],
        ),
    ]
