# Generated by Django 4.0.2 on 2023-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='county',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='curriculum',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='orientation',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='sub_county',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='tel',
            field=models.CharField(default='', max_length=80),
        ),
    ]
