# Generated by Django 4.0.2 on 2023-11-16 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_alter_doctor_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
