# Generated by Django 4.0.2 on 2023-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_doctor_issue_teacher_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tel',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='disability',
            field=models.CharField(choices=[('NONE', 'None'), ('BLIND', 'Vision Impairment'), ('DEAF', 'Hard of Hearing'), ('AUTISM', 'Autism'), ('PHYSICAL IMPAIRMENT', 'Physical Impairment'), ('COGNITIVE', 'Cognitive Impairment'), ('PSYCHOLOGICAL', 'Psychological Impairment')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=80),
        ),
    ]
