# Generated by Django 4.0.2 on 2024-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_school_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
