# Generated by Django 4.0.2 on 2024-01-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_issue_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='Condition',
        ),
    ]
