# Generated by Django 4.0.2 on 2023-09-28 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_rename_name_doctor_email_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
