# Generated by Django 4.0.2 on 2023-08-08 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_rename_name_doctor_first_name_doctor_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
